[package]
name = "rust_deps_bundle"
version = "0.1.0"
edition = "2021"

[dependencies]
torus-cpu = { path = "../../backends/torus-cpu/implementation", features = [
    "nightly",
] }
torus-cpu-noise-model = { path = "../../backends/torus-cpu/noise-model" }
torus-optimizer-cpp = { path = "../../compilers/torus-optimizer/torus-optimizer-cpp" }

[lib]
crate-type = ["staticlib"]
